image: cb/c7py36dj111:v2

stages:
  - test

job1:
  stage: test
  script:
    - pip3.6 install pip-accel
    - pip-accel install --requirement requirements.txt
    - python3.6 manage.py test --noinput
  tags:
    - test
